### ISSUE TITLE
Inaccurate wiki

### ISSUE THREAD

**Issue by sussyforwut** [Taureon/aps-plus-plus#106]
In the wiki, it says that `app.js` is where you can change the colors, when it's **_actually_** `gameDraw.js`
Practically unusable, please fix **_/j_**                      (note: the line above is serious)

**Comment by Trioplane** [comment]
wiki is not maintained rn lol but ill change it btw you can make colors serverside too by doing `COLOR: '#RRGGBB'`

**Comment by Zenphia** [comment]
could've put a /hj in there anyway but ok the wiki's fixed now bye

**Comment by sussyforwut** [comment]
cool
