### ISSUE TITLE
Game runs at half FPS in Firefox

### ISSUE THREAD

**Issue by Zenphia** [Taureon/aps-plus-plus#110]
Title's self-explanatory. I'm getting 30 FPS when I should normally be getting 60 FPS.

May not seem like that much of a difference, but running APS++ feels noticeably choppier than usual.

**Comment by Taureon** [comment]
We have to optimise a decent amount of the client and server before releasing beta 10

**Comment by Zenphia** [comment]
Isn't beta 10 already out? Don't you mean beta 11?

**Comment by hussainabidi1** [comment]
this is github not disocrd lol

**Comment by Taureon** [comment]
> Isn't beta 10 already out? Don't you mean beta 11?

still used to single digit beta numbers lol

**Comment by Zenphia** [comment]
Seems to only affect Firefox (and its forks) in my testing. Ungoogled-chromium runs at a smooth 60 FPS.

**Comment by Zenphia** [comment]
okay now ungoogled-chromium is running at 30fps for some reason

**Comment by Taureon** [comment]
time to learn how to diagnose performance

**Comment by Zenphia** [comment]
seems fixed
