### ISSUE TITLE
you cant damage rare alpha and beta pentagons with bullets

### ISSUE THREAD

**Issue by idkwhattoget** [Taureon/aps-plus-plus#111]
you can only damage them with body damage

https://github.com/Taureon/aps-plus-plus/assets/131004524/93807aed-8cc2-4015-874f-125e8fca26e5

**Comment by idkwhattoget** [comment]
the same thing also happens to rare eggs but those cant spawn naturally and there arent generators for them so its fine

**Comment by RanarTheWrathful** [comment]
It is an issue, but doesn't game breaking denote that it ruins the experience or the ability to play the game?

**Comment by Frostbyte178** [comment]
nan penetration body stat, fixed
