### ISSUE TITLE
Tanks in addons that use functions (like makeAuto) copy parent tank's upgrades

### ISSUE THREAD

**Issue by Zenphia** [Taureon/aps-plus-plus#116]
Can lead to upgrade recursion in the worst case scenario. Manually blanking the newly created tank's upgrades seems to work as a soft-fix.

**Comment by Taureon** [comment]
fixed in https://github.com/Taureon/aps-plus-plus/commit/ef14104965a9b087c409be1646a5b2d650ea942f
