### ISSUE TITLE
Turrets miss when their parent moves

### ISSUE THREAD

**Issue by Taureon** [Taureon/aps-plus-plus#12]
move perpendicular to whatever your turret is aiming at, and they will miss, even if its a shape
fix: make turrets snap or move faster for small angles

**Comment by Frostbyte178** [comment]
does this fix actually work or is it a bullet speed falloff issue

**Comment by ClashTest311** [comment]
It probably is bullet speed falloff issue at some point, but it's still is possible to make auto turrets more accurate

**Comment by Taureon** [comment]
fixed in https://github.com/Taureon/aps-plus-plus/commit/fc763b4fc7c8653f9da2ee6628d464f181e8e18a
