### ISSUE TITLE
Opposite of UPGRADES_TIER_#.push that removes a specific tank from tank upgrades

### ISSUE THREAD

**Issue by Zenphia** [Taureon/aps-plus-plus#120]
Just in case you make an addon that adds a hybrid trapper to bridge the gap between trapper and overtrapper and you don't wanna hardcode the Trapper's T3 upgrades just to get rid of overtrapper. If the specified tank to be removed isn't there anyway (if you manually removed overtrapper from trapper's T3s even with the addon installed) it'll just ignore it.

**Comment by idkwhattoget** [comment]
iirc this is a feature in js

**Comment by Zenphia** [comment]
Okay, turns out I just needed a bit of JS knowledge. Thanks idkwhattoget.
