### ISSUE TITLE
Config Stat Multipliers

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#122]
Basically it allows you to edit stats in config, something like this
HEALTH_MULTIPLIER: 2 //the health stat is multiplied by this.
This basically allows you to edit things like health, damage, penetration, density, etc on a global scale.

**Comment by Taureon** [comment]
you can do that in constants.js in definitions

**Comment by Frostbyte178** [comment]
just use base in constants.js
