### ISSUE TITLE
Guns with the ability to choose randomly from a list of projectiles to spawn

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#126]
Self explanitory, imagine if I wanted a class that uses sentries, but didn't want each barrel to be assigned a specific drone,instead, I can have a random choice between trap, swarm or gun sentries.
Evolving for people who want drones that act similar to polygons .

**Comment by 0Richardson2023** [comment]
well fuck

**Comment by Frostbyte178** [comment]
use ON - not commonly used enough to be implemented as an actual feature but we can help write the function
