### ISSUE TITLE
Room setup stuff.

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#128]
Allow things to enable like:
- NEST, this automatically places a nest at the center of map so you don't have to manually add the nest if you don't want to.
- OBSTACLES, ["mapCorners", "nestCorners", "wholeMap"], similar premise
- BASES, puts bases in each corner of the map if its 4 teams, or 2 on opposite sides if 2 teams.
- BASE_PROTECTORS, decides whether or not you want base protectors.

**Comment by Taureon** [comment]
thats way too specific, i prefer the overlay system that already allows this to be possible

**Comment by Trioplane** [comment]
look, in config.js the room setup is `["map_apspp_default"]` and in tdm.js its `["tdm_something"]` first it makes the whole map using map aps default the  overlays the tdm map to the current map

**Comment by Taureon** [comment]
> Overlay system?

here are certain room files that mostly consist of "undefined tiles", which dont replace the previously loaded tile in that same spot
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/ae4cd57c-0ec8-4282-ae2c-c393439b5de8)

with the ability of loading multiple maps at once on server start if a gamemode config also contains a map file to load, you can make use of the overlay system to simply add (for example) portal tiles to the map without having to make a whole dublicate map
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/05fb143b-5fab-460f-90de-707447b9cc73)
