### ISSUE TITLE
Sanctuaries Dissapearing

### ISSUE THREAD

**Issue by EmpressChong** [Taureon/aps-plus-plus#132]
After they get destroyed, they dissapear. Forever.
![image](https://github.com/Taureon/aps-plus-plus/assets/149181559/adb703f8-9efe-4aa1-9085-994caab08f92)

**Comment by Zenphia** [comment]
fixed, apparently the IsAC function needs terminal debugging whoops

**Comment by EmpressChong** [comment]
Nice
