### ISSUE TITLE
Turrets can occasionally glitch out when reloading your tab

### ISSUE THREAD

**Issue by Zenphia** [Taureon/aps-plus-plus#134]
Most noticeable with Diamond Marauder, DOG, and Healer branch. Their turrets just don't show up at all, which can cause issues (most noticeably with DM + DOG)

**Comment by Taureon** [comment]
with glitching out, what do you mean?

**Comment by idkwhattoget** [comment]
they dont render incorrectly they just vanish (or at least its like that for me)

**Comment by Zenphia** [comment]
edited, added clarification

**Comment by Frostbyte178** [comment]
the turret's facing is nan'd somehow, fixing
