### ISSUE TITLE
cant add tanks

### ISSUE THREAD

**Issue by connor11016** [Taureon/aps-plus-plus#137]
### `
this thing that i cant add tanks is![binicon](https://github.com/Taureon/aps-plus-plus/assets/125762682/248e99ae-249b-430f-8e22-388de8d8734b)
`

**Comment by EmpressChong** [comment]
what the hell are you talking about

**Comment by connor11016** [comment]
i cant add tanks

**Comment by Sontrux** [comment]
i have a strong feeling you know nothing about coding
