### ISSUE TITLE
Addons can't use `.push()` on certain tanks that have some `UPGRADE_TIER_#` undefined.

### ISSUE THREAD

**Issue by Trioplane** [Taureon/aps-plus-plus#138]
This causes conflicts between addons that use `Class.tank.UPGRADE_TIER_# = []` because `.push()` doesn't work.

Like on these situations where:
>----------------------------------
Addon 1 - adds an upgrade to auto spawner
```js
//Class.autoSpawner.UPGRADES_TIER_3.push() ❌ Will cause an error
Class.autoSpawner.UPGRADES_TIER_3 = ["myTank"]
```

Addon 2 - also addds an upgrade using the same method
```js
Class.autoSpawner.UPGRADES_TIER_3 = ["myCoolerTank"]
```
>----------------------------------
What will happen is `addon1.js` will get run first adding their `myTank` to the `autoSpawner.UPGRADES_TIER_3` but `addon2.js` will override it replacing it with their `myCoolerTank` because `.push()` will not work here unless specified in `tanks.js`

**Comment by Frostbyte178** [comment]
attemptPush util function coming right up even though it’s 4 lines of code via try-except

**Comment by Frostbyte178** [comment]
![Screen Shot 2023-12-03 at 10 10 35 AM](https://github.com/Taureon/aps-plus-plus/assets/65914790/ec2ccc37-7293-4a78-87fc-465613579c18)

**Comment by Taureon** [comment]
`--force`
