### ISSUE TITLE
Defining undefined entity.

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#143]
Instead of causing a crash when a undefined entity is trying to be used, make it define as a generic entity, that way if something is wrong, the problem is known without messing up the server.

**Comment by Frostbyte178** [comment]
why is an undefined entity being defined in the first place

**Comment by Frostbyte178** [comment]
used I mean, not defined, plus the default definition is the genericEntity and it’s defined as such when the entity is created in the constructor

**Comment by RanarTheWrathful** [comment]
Generally just typos, I know its likely easy to fix but I can imagine someone using a entity but mis type it without knowing and when people play on their server, boom, random disconnect. I personally would rather have a tiny dot spawning as opposed to a server crashing.

**Comment by Taureon** [comment]
this would cause more issues than it would fix.
a person who unknowingly made a typo would wonder why their definition doesn't work at all.

**Comment by RanarTheWrathful** [comment]
Fair enough.

**Comment by Frostbyte178** [comment]
now it crashes and gives more clear info
