### ISSUE TITLE
Satellite orbiting speed is faster than usual when upgrading from a tank with satellites

### ISSUE THREAD

**Issue by Zenphia** [Taureon/aps-plus-plus#146]
https://github.com/Taureon/aps-plus-plus/assets/93544652/a351f920-4e4b-440d-9beb-946d91f7e860

**Comment by idkwhattoget** [comment]
what would satellite speed affect?

**Comment by Frostbyte178** [comment]
fixed with duplicate controllers fix

**Comment by Zenphia** [comment]
now we just gotta figure out how to get the tempest/blizzard working :trollface:
