### ISSUE TITLE
Whirlwind issues

### ISSUE THREAD

**Issue by Trioplane** [Taureon/aps-plus-plus#149]
## Controlling Radius
- Currently, You have to keep holding `fire` or `altFire` to change the radius, if not it will go back to its original state, This is not how it works in arras.

## Whirlwind Deco Speed
- they dont match

**Comment by Frostbyte178** [comment]
were they synced? I don't remember that

**Comment by Trioplane** [comment]
After watching some cringe videos, They aren't exactly tied to each other but the speed is similar and currently it is not.

**Comment by Trioplane** [comment]
radius is fixed

**Comment by Zenphia** [comment]
No, this isn't a bug. You're definitely misremembering that. It's way more awkward to control when it doesn't go back to its original state.

**Comment by idkwhattoget** [comment]
i swear that you didnt need to hold them

**Comment by Zenphia** [comment]
hang on lemme look for some footage

**Comment by Zenphia** [comment]
ok nvm my memory sucks
