### ISSUE TITLE
Glitch currently is not working.

### ISSUE THREAD

**Issue by WaitWhatGliches** [Taureon/aps-plus-plus#150]
It seems glitch isnt updated to the current node version. it says Object.fromEntries is not a function.

**Comment by WaitWhatGliches** [comment]
it has node v10.24.1 according to glitch.

**Comment by DELTAFYREX** [comment]
Glitch is weird man.

**Comment by Trioplane** [comment]
APS++ now requires node 18 and above, iirc glitch doesn't have that

**Comment by Taureon** [comment]
will monkeypatch that weirdness when i get home later by just defining that method if it doesn't already exist
