### ISSUE TITLE
Bot Spawning

### ISSUE THREAD

**Issue by WaitWhatGliches** [Taureon/aps-plus-plus#151]
The game wont spawn bots, when it tries to spawn bots it crashes. 

![Screenshot 2023-12-19 10 30 43 AM](https://github.com/Taureon/aps-plus-plus/assets/97320923/8ca74d25-3da0-4cba-9905-5c4f25b109a3)

**Comment by ClashTest311** [comment]
well thats bc these bots dont have controllers at all ig

**Comment by ClashTest311** [comment]
its fixed btw
