### ISSUE TITLE
whirlwind bullets die when hitting walls

### ISSUE THREAD

**Issue by Siecelesness** [Taureon/aps-plus-plus#154]
![image_2023-12-24_220515980](https://github.com/Taureon/aps-plus-plus/assets/133080315/6fce9b3b-9a8e-4b23-b56e-dc30402b171a)
![image_2023-12-24_220524419](https://github.com/Taureon/aps-plus-plus/assets/133080315/6fb85668-96c2-4833-aca9-eed39404c1f5)

**Comment by Frostbyte178** [comment]
unsure if the daily tanks addon still has a copy of whirlwind in it, the stuff built-in now works fine
