### ISSUE TITLE
rare shapes go gigantic in growth

### ISSUE THREAD

**Issue by YanisDiss** [Taureon/aps-plus-plus#163]
can u make it so growth doesnt affect shapes
![Screenshot (155)](https://github.com/Taureon/aps-plus-plus/assets/77635886/8a6ade45-5161-4c0a-9c00-72ad449b23ab)

**Comment by idkwhattoget** [comment]
this is a thing in normal arras too

**Comment by Zenphia** [comment]
Duplicate of https://github.com/Taureon/aps-plus-plus/issues/156

**Comment by Zenphia** [comment]
Not actually a duplicate, whoops
