### ISSUE TITLE
Legendary Hexagons being indistinguishable from normal.

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#175]
I suppose I'm not 100% sure about this, I am guessing, but I'm sure no one thought about this, hexagons are the same colors as legendaries, so besides a kill message and a sudden boost in score, you can't tell them apart, I suggest making them yellow for their legendary counter parts, like the jewel. I had mentioned this to Damocles too but was probably ignored.

**Comment by Taureon** [comment]
i would make it yellow if it wasnt a "massive difference" in comparison to arras.io

**Comment by Frostbyte178** [comment]
why not do it anyway

**Comment by Taureon** [comment]
actually good point

**Comment by Taureon** [comment]
https://github.com/Taureon/aps-plus-plus/commit/841329cea4bc51bd008f0e8d6570b50bd1fbd14a

**Comment by RanarTheWrathful** [comment]
Wait, what is the "massive difference"?

**Comment by Taureon** [comment]
maybe people would think that its too big of a difference compared to arras.io

**Comment by Zenphia** [comment]
changed to the same colour that old dreads uses for its hexagons

**Comment by RanarTheWrathful** [comment]
> maybe people would think that its too big of a difference compared to arras.io

Well you did talk about fixing what is broken in arras.io, I don't think people will flip out about a color change since they can just change it back.
