### ISSUE TITLE
Suggestion for upgrades preview

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#180]
So uh Taureon said we should suggest stuff here even tho it's called issues so I'm putting it here (Tell me if that's not the right place either).

**UPGRADE PREVIEW MANUAL OFFSET**

`UPGRADE_OFFSET: [{size}, {x offset}, {y offset}],`
As of right now, the automatic sizing and positioning of the tank preview works pretty well for simple tanks, but as soon as you start putting complex designs it goes crazy. So I suggest this property: by default, it is blank which lets the upgrade auto-adjust itself. But if you see it doesn't do it correctly, you can define it as shown to manually set it as you like!

I have no idea how to implement that but that would be very useful imo (at least for me)

**Comment by Taureon** [comment]
fyi this label exists, so issues is fine for everything 👍 
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/b05dc2a8-d045-45e5-9ac3-704e3f4cd22e)

**Comment by Taureon** [comment]
also, i think something better than this would be "fix the mockup generator dying every now and then" because thats mostly at fault
