### ISSUE TITLE
9 addons are not working

### ISSUE THREAD

**Issue by connor11016** [Taureon/aps-plus-plus#182]
I just wanted to add all the addons :(

**Comment by Frostbyte178** [comment]
which ones

**Comment by connor11016** [comment]
dailytanks.js diep.js diep2.js effectroller.js legacytanks.js moarautos.js moarflanks.js moremysticals.js and retrograde.js

**Comment by AydanL** [comment]
are those all up to date? Cuz after the yearly heavy changes many addons were no more compatible until they were updated

**Comment by Zephiii** [comment]
We are aware of this. I put up a hotfix a while back but that doesn't seem to have resolved everything. I'll get a permanent fix done by the end of February as I've got a busy schedule.

**Comment by Zephiii** [comment]
This isn't actually the place to report bugs with addons, do so [here](https://github.com/Taureon/aps-plus-plus-addons)
