### ISSUE TITLE
nest keeper

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#186]
Its side turrets should be grey not purple

**Comment by Zephiii** [comment]
If something doesn't match how it is in Arras.io, **change it yourself**.

We are not trying to copypaste everything Arras.io does, good or bad. If we did, we would've had the controversial Conqueror nerf and teal Hexagons.

The Nest Keeper intentionally uses purple turrets to match the other two Nesters. Changing just it and not the others purely out of parity is weird.
