### ISSUE TITLE
Hexanoughts wrong color

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#187]
for some reason hexanoughts are always purple instead of teal... weird isn't it?

**Comment by Frostbyte178** [comment]
aps++ hexagons are magenta so the dreads are too, I can add a toggle later

**Comment by AydanL** [comment]
oh lol didn't know you eventually switched hexagons to magenta

**Comment by Zephiii** [comment]
closed as works as intended

**Comment by Zephiii** [comment]
reclosed as "fixed" now that arras.io actually differentiates hexas and legendaries
