### ISSUE TITLE
Underseer drone cap issue

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#194]
I noticed issues on the underseers' drone count cap long ago, and just now I decided to take a closer look on it. After several testings, it turns out this:
- After the sunchip cap is reached, spawners stop spawning drones (which is normal)
- Sunchips can still pick squares under certain conditions which are:
       - They can only pick squares that spawned before the cap was reached (or another event that includes some squares and not others)
       - They stop picking them after a set sunchip count which seems to be (didn't count exactly) the double of the theorical cap.
This is weird and obviously unintended (?) so ig it would be nice to fix it...

Btw for some reason can't add labels on issues here unlike aps-plus-plus-addons, probably because I don't have perms here :/

**Comment by Frostbyte178** [comment]
fixed
