### ISSUE TITLE
Certain upgrades appear weirdly in upgrade menu

### ISSUE THREAD

**Issue by Zephiii** [Taureon/aps-plus-plus#196]
<img width="864" alt="Screenshot 2024-02-24 at 09 40 35" src="https://github.com/Taureon/aps-plus-plus/assets/93544652/b843e0e1-2275-4d60-9120-971f8b5bb594">

**Comment by Frostbyte178** [comment]
oops

**Comment by Zephiii** [comment]
more stuff: still happening with ATMGs and the "don't upgrade" button is misaligned
![image](https://github.com/Taureon/aps-plus-plus/assets/93544652/5e01302b-4f97-4c76-946a-d7fe473df18b)

**Comment by Zephiii** [comment]
@Frostbyte178 definitely not fixed
<img width="110" alt="Screenshot 2024-04-04 at 22 55 30" src="https://github.com/Taureon/aps-plus-plus/assets/93544652/85a11c17-9dc9-4181-81e1-a43236488f95">

**Comment by Frostbyte178** [comment]
reopen if something comes up again
