### ISSUE TITLE
Bug on mockup

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#197]
Interresting issue, when you batch classes the mockup size will be based on the size of the first tank of the array. For example, the upgrade 
`UPGRADES_TIER_0: [[ "ranger", "spike" ]]` 
will be sized based on the ranger mockup but 
`UPGRADES_TIER_0: [[ "spike", "ranger" ]]` 
won't because the body will be as big as a regular spike would be.
Hope I explained well

**Comment by AydanL** [comment]
The more I use it the more bugs i find... On top of said issue, the tank printing is broken when invisibilible

**Comment by Frostbyte178** [comment]
wdym tank printing

**Comment by AydanL** [comment]
i mean the drawing, I showed pic on discord arras-coding
