### ISSUE TITLE
Prop glitch ig

### ISSUE THREAD

**Issue by TheExecutionist0** [Taureon/aps-plus-plus#199]
When an entity gets defined from a different tank that has props, the props don't clear on the defined tank. This happens because props don't get cleared in the same manner turrets are.

I suggest replacing the current set.PROP != null if statement with this:
![Screenshot 2024-03-01 12 46 38 PM](https://github.com/Taureon/aps-plus-plus/assets/150874204/65db5c91-4940-4bef-9174-d73a38ca1abb)

**Comment by Frostbyte178** [comment]
props and turrets are cleared the same way - if the define input has turrets
genericEntity and genericTank have empty arrays for turrets and props
I can change the define fn to auto clear turrets and props but currently they should work identically

**Comment by TheExecutionist0** [comment]
Well when I implemented aps++'s prop code, it began doing that... I made sure to check for discrepancies or missing content but that didn't seem to be the issue, idk. ig this is what I get for not updating aps++ the "intended" way

**Comment by Frostbyte178** [comment]
copy the PROPS: [] in genericTank and genericEntity
