### ISSUE TITLE
[IMPORTANT] From now on, suggestions go to Discussions.

### ISSUE THREAD

**Issue by Zephiii** [Taureon/aps-plus-plus#208]
**We're only going to be accepting bug reports here from now on. This page is called _Issues_ after all.**

If you want to make a suggestion, do so [here](https://github.com/Taureon/aps-plus-plus/discussions/categories/suggestions). All currently open suggestions will be migrated there.

Any new suggestions here will be moved to the relevant Discussions channel.

**Comment by Taureon** [comment]
yeah i dont think so

**Comment by AydanL** [comment]
Fair, always though suggestions didn't belong in issues

**Comment by Zephiii** [comment]
Still keeping this pinned because it's just important for people to know.
