### ISSUE TITLE
Sanctuary Healer bullets go the wrong way

### ISSUE THREAD

**Issue by hellena369** [Taureon/aps-plus-plus#226]
![image](https://github.com/Taureon/aps-plus-plus/assets/70903165/7e9ee0f2-c8d3-4a56-acdd-705efde48132)
![image](https://github.com/Taureon/aps-plus-plus/assets/70903165/49373124-3c0a-4bdb-8ce4-b9a49067e426)
This is a fresh installation of APS++, and the sanctuary healing bullets seem to be a little strange.

**Comment by Zephiii** [comment]
Can reproduce

**Comment by ClashTest311** [comment]
That's what happens when you sad your bullet speed to low 💀

**Comment by ClashTest311** [comment]
Fixed with commit [Sanctuary fix](https://github.com/Taureon/aps-plus-plus/commit/1c089429d6e8ff08ad9d9b3180d336391ce50371)

**Comment by Frostbyte178** [comment]
actually fixed in 154f3f407bf2fd37f7827fa9d74581439198cffa
