### ISSUE TITLE
Healer Reload Craziness

### ISSUE THREAD

**Issue by hellena369** [Taureon/aps-plus-plus#228]
![image](https://github.com/Taureon/aps-plus-plus/assets/70903165/68544bde-4582-45c7-9ed7-8f132ed74f36)
![image](https://github.com/Taureon/aps-plus-plus/assets/70903165/3449471a-f3ca-42ff-accf-a81a08e2b3df)
Well, you may have made healers shoot straight but now they are machine guns.

**Comment by Frostbyte178** [comment]
3ee90519369e9a35d8cf897d92e34f3852724f6a
