### ISSUE TITLE
Image Shapes do not work

### ISSUE THREAD

**Issue by Trioplane** [Taureon/aps-plus-plus#232]
Trying to use an image path by using strings in `SHAPE`, Nothing will render.

##  Intended Behavior
`SHAPE: "osa_background_tile.png"` -- Renders the osa_background_tile image
`SHAPE: "afajiufheieufhiufhi.png"` -- Renders the missing texture shape.

**Comment by Frostbyte178** [comment]
they were intended to work with just urls, expanding to file paths as well
