### ISSUE TITLE
leaderboard/scoreboard

### ISSUE THREAD

**Issue by ChandlerAx** [Taureon/aps-plus-plus#237]
Try open 3 alts, max score and look leaderboard its bugged by showing up so try fix this and also add multi cpu core support

**Comment by ClashTest311** [comment]
Fixed in [Leaderboard fix](https://github.com/Taureon/aps-plus-plus/commit/02c6c5dd092ccbd03d3bbce33781e43b8c1f1be4)

**Comment by Taureon** [comment]
> and also add multi cpu core support

leaderboard rendering does not need multicore support

**Comment by ChandlerAx** [comment]
> > and also add multi cpu core support
> 
> leaderboard rendering does not need multicore support

I mean multi-core support on the overall server, it seems like it only uses 1 cpu thread for some reason (then the server starts lagging), probably the network is limited to 1 core or something, cant find it out or use multi processes

**Comment by Taureon** [comment]
> > > and also add multi cpu core support
> > 
> > 
> > leaderboard rendering does not need multicore support
> 
> I mean multi-core support on the overall server, it seems like it only uses 1 cpu thread for some reason (then the server starts lagging), probably the network is limited to 1 core or something, cant find it out or use multi processes

that would be a different issue then. an issue that would be very difficult to solve

**Comment by ChandlerAx** [comment]
> > > > and also add multi cpu core support
> > > 
> > > 
> > > leaderboard rendering does not need multicore support
> > 
> > 
> > I mean multi-core support on the overall server, it seems like it only uses 1 cpu thread for some reason (then the server starts lagging), probably the network is limited to 1 core or something, cant find it out or use multi processes
> 
> that would be a different issue then. an issue that would be very difficult to solve considering the state of the server

Adding multiple process threads shouldn't be that hard, but I would really look into it or other solutions because if it ends up on 1 cpu thread (process cap limit) the server starts to lag
