### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ChandlerAx** [Taureon/aps-plus-plus#241]
It appears that five active instances of Octo are utilizing only one CPU thread, which is suboptimal. Given that Node.js restricts execution to a single CPU thread, try find viable solutions. The attached image CPU utilization at 100% on one thread, despite available unused CPU threads. This issue must be promptly addressed to ensure server scalability for accommodating 10 to 50 players.

Also not only octo, simple a few players and it uses to much performance, multi core/process support would be great
![image](https://github.com/Taureon/aps-plus-plus/assets/151396622/4f7b2e5c-ed90-4ecf-a0bd-4eae1bda7706)

**Comment by Taureon** [comment]
if multithreading were easy, it would be done so by now

**Comment by ChandlerAx** [comment]
> if multithreading were easy, it would be done so by now

Just use cluster module and multi process the networking/tanks, bullets etc 

Also simple example of each process communication

Example: 
```javascript
cluster.on('message', (worker, message) => {
    console.log(`${worker.id} said:  ${message}`);
});
// Inside the process you use `process.send('data123')`;
// Supports arrays etc as well
```

Full example:
```javascript
const cluster = require('cluster');
const numCPUs = require('os').cpus().length; // run 1 process for each possible cpu thread

if (cluster.isMaster) {
  console.log(`main ${process.pid}`);

  for (let i = 0; i < numCPUs; i++) {
    const worker = cluster.fork();

    worker.on('message', (message) => {
      console.log(`${worker.process.pid}:`, message);
    });
  }
} else {
  const payload = { workerId: process.pid, message: 'hello from process' };
  process.send(payload);
}
```

**Comment by Taureon** [comment]
we dont use npm modules here. also this will not fix the problem of singular servers not splitting up entity calculations among multiple cores

**Comment by ChandlerAx** [comment]
> we dont use npm modules here. also this will not fix the problem of singular servers not splitting up entity calculations among multiple cores

Load balancing each instruction over all processes is possible and what do you mean no modules there are modules anyway in-build by running nodejs

And besides, someone should make the server in Go lang or Python f@ck nodejs, it's the slowest possible language ever made in the coding history (its not made for backend game servers)

**Comment by VOID4487** [comment]
Wow , suggestion for a rewrite when the gameserver is half completed and the bug fixing with those other language is also going to eat hours.

**Comment by Frostbyte178** [comment]
post in discussions instead
