### ISSUE TITLE
Disconnected: Socket error

### ISSUE THREAD

**Issue by synt4ctic** [Taureon/aps-plus-plus#245]
I have an instance running on my Raspberry Pi with the latest version of Node.js and NPM. When I go to http://localhost:23601, it gets stuck on "Connecting..." and when I click play, it displays the error: "Disconnected: Socket error". I installed the ws package with `npm install ws` so I do not think that's the issue.

**Comment by Taureon** [comment]
unless you are checking out the game directly on your raspberry pi, you would have to change localhost to your pi's local network ip (`192.X.X.X`) and then use *that* to connect to the aps++ instance.
let me know how that works

**Comment by synt4ctic** [comment]
I know, I was accessing it from a Cloudflare tunnel. I also tried accessing it from its IP on my network, same issue.

**Comment by Taureon** [comment]
if you put localhost in your browser, it expects a webserver to be on the same machine that is visiting localhost
btw, what are the errors in devtools console?

**Comment by ChandlerAx** [comment]
> [localhost:23601](http://localhost:23601), it

Set host url in server/config.js to localhost:26301

**Comment by synt4ctic** [comment]
There was a websocket error:
`socketInit.js:754 WebSocket connection to 'wss://localhost:26301/' failed: `

**Comment by Taureon** [comment]
when you connect to the server, does the server's console log anything?

**Comment by synt4ctic** [comment]
Not any errors on the server's console itself, but there was the websocket error in the developer console

**Comment by Taureon** [comment]
> There was a websocket error: `socketInit.js:754 WebSocket connection to 'wss://localhost:26301/' failed: `

what is the host variable in the config file?

**Comment by synt4ctic** [comment]
`localhost:23601`

**Comment by Taureon** [comment]
change that to the domain that you've been putting in the url bar the entire time and then restart the server

**Comment by synt4ctic** [comment]
Thank you, that worked
