### ISSUE TITLE
i did some stuff and then strange stuff happens (note: this is VERY MUCH just something im doing wrong but i dont like chattin on discord so imma ask here))

### ISSUE THREAD

**Issue by sussyforwut** [Taureon/aps-plus-plus#252]
so i added some stuff to the thing (a new polygon and a new animated color (five bars) ) then i added the custom polygon in the polygon generator thing in config.js, i ran the run.bat, went to the localhost, but when i pressed 'play', the screen is blank except for the background. plz just tell me the issue.

**Comment by Taureon** [comment]
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/04de31ca-286e-4b48-84bf-f11f624631cb)
open devtools and screenshot the errors you would see here.
if your screen is blank it should tell you what the error is

**Comment by sussyforwut** [comment]
k

**Comment by sussyforwut** [comment]
the error is that my colors are not defined

**Comment by sussyforwut** [comment]
![Capture](https://github.com/Taureon/aps-plus-plus/assets/103869137/ee2bf991-bf93-447a-ac8b-f66b3a0d0578)

**Comment by Taureon** [comment]
you should define that variable correctly if you can spot the mistake

**Comment by sussyforwut** [comment]
![Capture](https://github.com/Taureon/aps-plus-plus/assets/103869137/e8628080-737a-47fa-8ff1-0a276608cb6f)

**Comment by Taureon** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/103869137/338576095-e8628080-737a-47fa-8ff1-0a276608cb6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDgwNjUsIm5iZiI6MTcxODEwNzc2NSwicGF0aCI6Ii8xMDM4NjkxMzcvMzM4NTc2MDk1LWU4NjI4MDgwLTczN2EtNDdmYS04ZmYxLTBhMjc2NjA4Y2I2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTkzN2Q1NThjNGUwNGY5ZGIwZGEzMmYxZTkxZThjNDgwMTYwMDk5MmZlMmNhZTE4NGQ3ODdmZjNiMDQ3YjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A_tM0YV4jbCzTX3V56Q0JbWN70oG8bC4yX2QXftAqbs)

change that `;` into a `,` after the trans colors

**Comment by sussyforwut** [comment]
thx now i got it workin

**Comment by Taureon** [comment]
👍

**Comment by sussyforwut** [comment]
![Uploading Capture.png…]()

**Comment by sussyforwut** [comment]
epic now its done
