### ISSUE TITLE
yanisdiss arras.io addon broken

### ISSUE THREAD

**Issue by connor11016** [Taureon/aps-plus-plus#256]
[theres a community addon by yanisdiss that does that and with like dozens of times more tanks](https://github.com/YanisDiss/UltimateCloserPack-Addon/)

_Originally posted by @Taureon in https://github.com/Taureon/aps-plus-plus/discussions/253#discussioncomment-9863201_
it doesnt work

**Comment by Taureon** [comment]
i am not the repository owner, yanisdiss is.
go ask them
