### ISSUE TITLE
Config Addition: Obstacle Intensity

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#266]
I added this to my server and I thought it would be a good addition to aps++ too.
Basically its a config option(OBSTACLE_INTENSITY) that allows you to reduce or increase the # of rocks by multiplying the rock count by this setting(OBSTACLE_INTENSITY: 1 will be normal amount, OBSTACLE _INTENSITY: 0 will be no obstacles, and OBSTACLE_INTENSITY: 0.5 would be half the normal amount, etc).

**Comment by Frostbyte178** [comment]
put in discussions
