### ISSUE TITLE
Whirlwind 2.0

### ISSUE THREAD

**Issue by anguish0800** [Taureon/aps-plus-plus#267]
Would be cool if whirlwind 2.0 came to aps++ considering it's a DOPE addition to I'm pretty sure sadly it's scrapped, would be in the unavailable menu
![Screenshot_2024-07-27-00-53-14-349_com google android youtube-edit](https://github.com/user-attachments/assets/1bcc3a55-24a7-4c1c-9335-4c32e88bfd29)

**Comment by Frostbyte178** [comment]
discussions tab is for suggestions, issues tab is for issues
