### ISSUE TITLE
Player UI No Longer Appears

### ISSUE THREAD

**Issue by khoa0428** [Taureon/aps-plus-plus#269]
Upgrade stats menu no longer appear when you hover your mouse over the bottom left corner or when you level up. Player name, level xp and the leaderboard also no longer show up.

Here is the image of my screen when my tank is level 45 (I could tell since all the upgrade branches appears and I can no longer get bigger)

![Screenshot 2024-07-28 125255](https://github.com/user-attachments/assets/637eae02-92e2-4a13-b1ed-3b61dbe65238)

**Comment by Frostbyte178** [comment]
settings -> ui elements
updating in a future commit to be enabled by default
