### ISSUE TITLE
Some transparent item no longer appears.

### ISSUE THREAD

**Issue by khoa0428** [Taureon/aps-plus-plus#270]
Eventhough tanks aura still does damage, it doesn't showed up. For example in my image below, dread's aura does damage to the triangle. And note that not only the dread aura but all aura seems to have this same issue.
<img width="266" alt="image" src="https://github.com/user-attachments/assets/ec055f3f-a439-4959-9f4d-3be3d03e9eed">
<img width="211" alt="image" src="https://github.com/user-attachments/assets/2872d50a-9701-4458-bbe8-a2ff4d8bd7fb">

This issue also for some reason applied for Spectator tank, which also no longer showed up. **_It might be an error in executing the ALPHA attribute._**

<img width="380" alt="image" src="https://github.com/user-attachments/assets/c1e98636-6273-425f-8891-1f7d5a705788">

**Comment by AE0hello** [comment]
Enable fancy animations at the options menu

**Comment by AE0hello** [comment]
![image](https://github.com/user-attachments/assets/bfb56012-255d-41f6-9926-28b37be67a28)
