### ISSUE TITLE
Bot tank mockups no longer appear on the leaderboard

### ISSUE THREAD

**Issue by WaitWhatGliches** [Taureon/aps-plus-plus#274]
![image](https://github.com/user-attachments/assets/52339b84-e010-43e9-bd5c-bea18a3a2966)

**Comment by Frostbyte178** [comment]
??????????

**Comment by WaitWhatGliches** [comment]
and bullets from bots are grey

**Comment by WaitWhatGliches** [comment]
that's been a issue for me for a while

**Comment by Frostbyte178** [comment]
can't reproduce the color, fixed the mockup thing
