### ISSUE TITLE
A majority of bullets and only bullets are appearing grey for some reason despite never being modified in color.

### ISSUE THREAD

**Issue by Droid-The-Shovel** [Taureon/aps-plus-plus#275]
![image](https://github.com/user-attachments/assets/54b865b3-713e-43ca-8005-07200d741aa3)
![image](https://github.com/user-attachments/assets/27cc8160-79ac-4c0e-a9ad-f961be72d2da)

**Comment by Frostbyte178** [comment]
cannot confirm
