### ISSUE TITLE
Siege Sanctuary Crash

### ISSUE THREAD

**Issue by WaitWhatGliches** [Taureon/aps-plus-plus#278]
This error happened after I killed a sanctary 2 times then tried to kill it again
(went to enemy team, my team, enemy (crash))

![image](https://github.com/user-attachments/assets/6a0c6582-60a7-4fbf-89cf-8625dc5be890)
![image](https://github.com/user-attachments/assets/e0388e5f-07e5-46b6-9fa0-a4311e7fa350)

**Comment by Frostbyte178** [comment]
old code was a bit of a wtf
