### ISSUE TITLE
when fancy animations are disabled everything with an opacity that isnt 1 doesnt render

### ISSUE THREAD

**Issue by DELTAFYREX** [Taureon/aps-plus-plus#296]

**Comment by Strange-Shotgun** [comment]
The same as #270 . Enable fancy animation to solve the problem.

**Comment by Strange-Shotgun** [comment]
The same as #270.
Seems this is intended. To solve this problem, go to app.js and replace
get() {
        return settings.graphical.fancyAnimations ? this.getLerp() : this.getNoLerp();
    }
with
get() {
        return this.getLerp();
    }

**Comment by Strange-Shotgun** [comment]
Sorry for the wrong comments.
This problem is the same as #270. This seems to be intended.
To modify fancyAnimation, go to app.js.

**Comment by Strange-Shotgun** [comment]
To solve the problem, go to public/app.js and replace
if (settings.graphical.fancyAnimations && assignedContext != ctx2 && (fade !== 1 || alpha !== 1))
with
if (assignedContext != ctx2 && (fade !== 1 || alpha !== 1))
that will do the thing.
(Hope there are no more mistakes)

**Comment by AE0hello** [comment]
This is NOT a bug, Transparent takes a lof of performance, This is why fancy animations are for.

**Comment by AE0hello** [comment]
@Strange-Shotgun  What you just did makes Fancy animations useless.
