### ISSUE TITLE
Level count seems 1 off.

### ISSUE THREAD

**Issue by DogeisCut** [Taureon/aps-plus-plus#3]
![image](https://github.com/Taureon/aps-plus-plus/assets/23178844/9c69ca13-c01f-47cb-ac3a-8f70445f737c)
Left is APS++
Right is arras.io

Both are freshly spawned players, yet aps++ reads level 0 while arras.io reads level 1

**Comment by DogeisCut** [comment]
on top of this, the maximum level up score is not the same.
![image](https://github.com/Taureon/aps-plus-plus/assets/23178844/0aeb76ba-b9da-4d64-b2b4-8903d079b41c)

**Comment by Taureon** [comment]
fixed in https://github.com/Taureon/aps-plus-plus/commit/bbd60df2a0174d8771b14216572f6418b5dce5e7
