### ISSUE TITLE
Contents in options menu are larger than the container

### ISSUE THREAD

**Issue by hussainabidi1** [Taureon/aps-plus-plus#53]
self-explanatory

**Comment by Taureon** [comment]
they do on my screen, could you show a screenshot?
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/a1f7bf7f-3c0c-406d-a4a8-aefbbc3b4581)

**Comment by hussainabidi1** [comment]
![image](https://github.com/Taureon/aps-plus-plus/assets/67141414/a1070b58-b630-4239-a1ab-c72e9dc51f7f)
It doesnt scroll either
its a bit clipped on your screen too do you see?

**Comment by hussainabidi1** [comment]
added scroll
opening pr
