### ISSUE TITLE
Instantly kicked from server despite putting no key in.

### ISSUE THREAD

**Issue by DogeisCut** [Taureon/aps-plus-plus#8]
![Code_sS3Xg6YQPw](https://github.com/Taureon/aps-plus-plus/assets/23178844/0a6b0b5a-9af4-4efa-9e64-a1f12f5b2c79)
Not sure what's up with this.
For now, I'm commenting out the code that checks if the key is valid.

**Comment by Taureon** [comment]
resolved here: 
https://github.com/Taureon/aps-plus-plus/commit/697ce2336d1d359078cd759dac65312b1a72911a
