### ISSUE TITLE
screen glitches out, i dont know why

### ISSUE THREAD

**Issue by syan0192** [Taureon/aps-plus-plus#82]
![Screenshot 2023-10-14 203123](https://github.com/Taureon/aps-plus-plus/assets/139653550/92a21672-a362-436e-a811-62ba53299cee)
![Screenshot 2023-10-14 202023](https://github.com/Taureon/aps-plus-plus/assets/139653550/936f3d8f-47a6-4c53-af7b-53c58b818a34)
![Screenshot 2023-10-14 202225](https://github.com/Taureon/aps-plus-plus
![Screenshot 2023-10-14 202753](https://github.com/Taureon/aps-plus-plus/assets/139653550/064bcff3-247c-4cc1-9cad-12626867c4d8)
/assets/139653550/081179fc-3dd6-47f0-ba92-47d490fc67e7)
![Screenshot 2023-10-14 202248](https://github.com/Taureon/aps-plus-plus/assets/139653550/2ca70adf-2b1c-4050-b9fa-2ad0a9ac8f86)

**Comment by Zenphia** [comment]
[Refer to the FAQ.](https://github.com/Taureon/aps-plus-plus/wiki/Frequently-Asked-Questions#something-weird-happened-and-the-screens-going-funky)
