### ISSUE TITLE
bots that have auras can leave them behind (unknown cause)

### ISSUE THREAD

**Issue by asdrubals** [Taureon/aps-plus-plus#83]
![image](https://github.com/Taureon/aps-plus-plus/assets/80239037/36de9e1d-f9fe-4084-9fb7-1cdb6104918f)

**Comment by 0Richardson2023** [comment]
There's sentient auras?????????

**Comment by Taureon** [comment]
we should finally get vulnerable turrets working imo

**Comment by Taureon** [comment]
we can just make auras turrets instead of hella weird bullets

**Comment by asdrubals** [comment]
Managed to witness exactly where it happens: when a bot upgrades while an aura is active. 
for some reason the aura is left behind, but the leftover aura still recognizes the bot as the master (because it clears when the bot dies, it just doesnt follow anymore)

**Comment by DogeisCut** [comment]
I believe vulnerable turrets is how the actual arras does it too

**Comment by Frostbyte178** [comment]
don’t think so, they lag behind the movement slightly, even when the client’s rotation is pulled from the server (delayed)

**Comment by Taureon** [comment]
> I believe vulnerable turrets is how the actual arras does it too

no, arras just spawns one fat bullet with a movement type that gives it attachment issues

**Comment by Taureon** [comment]
> don’t think so, they lag behind the movement slightly, even when the client’s rotation is pulled from the server (delayed)

ey, another reason to use vulnerable turrets for auras

**Comment by Frostbyte178** [comment]
cannot reproduce after leaving a server of 24 aura-basic bots running for 10 minutes while afking in a corner, marking as fixed, lmk if it still happens

**Comment by Trioplane** [comment]
@Frostbyte178 did you make them be able to upgrade?

**Comment by Frostbyte178** [comment]
still doesn't occur
