### ISSUE TITLE
Both t and f are opening the class tree.

### ISSUE THREAD

**Issue by DogeisCut** [Taureon/aps-plus-plus#9]
F is supposed to activate "Autoalt" (which I was told is autofire for alt fire but whatever).
F does activate it
but also opens the class tree for some reason???

https://github.com/Taureon/aps-plus-plus/assets/23178844/11f1addf-1199-4156-a4ba-3cea30a20ce5

**Comment by Taureon** [comment]
![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/e8a4408f-aeb7-4018-b8b3-c35ab1d168b2)
i am very smart yes
