### ISSUE TITLE
rare shapes with bigger sizes (like shiny alpha pentagon) that are created with generators are small

### ISSUE THREAD

**Issue by idkwhattoget** [Taureon/aps-plus-plus#91]
self explanatory
![image](https://github.com/Taureon/aps-plus-plus/assets/131004524/b87df472-09bb-409d-83b3-0f5167aa5939)

**Comment by Taureon** [comment]
thats weird
generator guns have `INDEPENDENT_CHILDREN`, so they should have their normal sizes

**Comment by Zenphia** [comment]
seems to affect labyrinth polygons as well

**Comment by Trioplane** [comment]
weird, it must be a bug with shinies cuz `INDEPENDENT_CHILDREN` work fine

**Comment by Trioplane** [comment]
![image](https://github.com/Taureon/aps-plus-plus/assets/87922281/6eb30d2c-236f-4d1f-8ed0-a5b543c0d23c)

**Comment by Taureon** [comment]
> seems to affect labyrinth polygons as well, shiny eggs are just nonexistent

talking about laby polygon sizes, i think i should rework how their size gets calculated
delta hexagon is incredibly small meanwhile delta triangle is competing in size with superbosses

**Comment by Taureon** [comment]
> ![image](https://user-images.githubusercontent.com/87922281/278870857-6eb30d2c-236f-4d1f-8ed0-a5b543c0d23c.png)

huh, thats definitely wrong LOL

**Comment by Trioplane** [comment]
> ![image](https://user-images.githubusercontent.com/87922281/278870857-6eb30d2c-236f-4d1f-8ed0-a5b543c0d23c.png)

i think this is whats causing the small sizes

**Comment by Taureon** [comment]
undoubtibly whats wrong, imma fix that

**Comment by Trioplane** [comment]
cuz,

Shiny Egg:

0 + 0

**Comment by Zenphia** [comment]
> 0 + 0

i misread that as 0 ÷ 0 lol

**Comment by Trioplane** [comment]
wait let me push my things first
