### ISSUE TITLE
Adding an underscore in `BRANCH_LABEL`'s value will make the client freak out

### ISSUE THREAD

**Issue by Trioplane** [Taureon/aps-plus-plus#95]
Example: `BRANCH_LABEL: 'SCENEXE_....'`

**Comment by 0Richardson2023** [comment]
uhhhh

**Comment by Frostbyte178** [comment]
this is what I get for using _ as a separator in string inputs
snake case gross though just don’t use it

**Comment by Trioplane** [comment]
`REROOT_UPGRADE_TREE` also doesnt like it when theres `_`
