### ISSUE TITLE
Add a custom timer length for broadcasts.

### ISSUE THREAD

**Issue by RanarTheWrathful** [Taureon/aps-plus-plus#96]
Idea is simple, its just like broad cast but with 2 different features:
- it does not decay, similar to the arena closed message found in diep.io.
- It can be modified, for things like adding a timer to it.

**Comment by 0Richardson2023** [comment]
Permanent*

**Comment by Frostbyte178** [comment]
add it as the second argument for the sendMessage function in the latest commit
