### ISSUE TITLE
cant level up infinitely

### ISSUE THREAD

**Issue by aconethirty** [Taureon/aps-plus-plus#97]
i used to be able to infinitely lvl up with N but now i cant, how can i fix it? i already reinstalled aps++ and i still cant lvl up infinitely

**Comment by Taureon** [comment]
make sure to use a token that has `infiniteLevelUp` set to true

![image](https://github.com/Taureon/aps-plus-plus/assets/45183108/dfd00b11-22af-458b-b2e1-a8deacf21e5b)

**Comment by aconethirty** [comment]
> make sure to use a token that has the `infiniteLevelUp` permission set to `true`
> 
> ![image](https://user-images.githubusercontent.com/45183108/279501773-dfd00b11-22af-458b-b2e1-a8deacf21e5b.png)
